local_backend: true
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/images/uploads
public_folder: images/uploads
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Gallerie"
      name: "Gallerie"
      file: "content/gallerie.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
        - label: "Pictures"
          name: "pictures"
          widget: list
          fields:
            - label: "Photo"
              name: "photo" 
              widget: "image" 
              media_library: 
                config: 
                  multiple: true
            - { label: "Name", name: "name", widget: "string"}
            - label: "Catégories"
              name: "categories"
              widget: select
              multiple: true
              options: 
                - { label: "Baptème", value: "bapt"}
                - { label: "Bébé", value: "baby"}
                - { label: "Famille", value: "fam"}
                - { label: "Grossesse", value: "preg"}
                - { label: "Mariage", value: "wed"}
                - { label: "Portrait", value: "por"}