# local_backend: true
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/images/uploads
public_folder: images/uploads
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Pictures'
          name: "pictures"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Caption", name: "Caption", widget: "text"}